<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="GridSample.aspx.cs" Inherits="JobPortal_Web.GridSample" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
     <div>
            <table>
                <tr>
                    <td>
                         <asp:GridView ID="JobPortalView" runat="server" AutoGenerateColumns="False" DataKeyNames="AccountId" AutoGenerateDeleteButton="True"
               AutoGenerateEditButton="True" onrowupdating="GridView1_RowUpdating" onrowcancelingedit="GridView1_RowCancelingEdit"   
                    onrowdeleting="GridView1_RowDeleting" onrowediting="GridView1_RowEditing" ShowFooter="true">
                <Columns>
                    <asp:TemplateField HeaderText="UserId" runat="server">
                <edititemtemplate>  
                                <asp:TextBox ID="TxtId" runat="server" Text='<%# Bind("AccountId") %>'></asp:TextBox> 
                                </edititemtemplate>
                <itemtemplate>  
                                <asp:Label ID="LabelId" runat="server" Text='<%# Bind("AccountId") %>'></asp:Label>  
                            </itemtemplate>
            </asp:TemplateField>
                     <asp:TemplateField HeaderText="FirstName" runat="server">
                <edititemtemplate>  
                                <asp:TextBox ID="TxtName" runat="server" Text='<%# Bind("FirstName") %>'></asp:TextBox> 
                                </edititemtemplate>
                <itemtemplate>  
                                <asp:Label ID="LabelName" runat="server" Text='<%# Bind("FirstName") %>'></asp:Label>  
                            </itemtemplate>
            </asp:TemplateField>
                    <asp:TemplateField HeaderText="Phone" runat="server">
                <edititemtemplate>  
                                <asp:TextBox ID="TxtPhone" runat="server" Text='<%# Bind("PhoneNumber") %>'></asp:TextBox> 
                                </edititemtemplate>
                <itemtemplate>  
                                <asp:Label ID="LabelPhone" runat="server" Text='<%# Bind("PhoneNumber") %>'></asp:Label>  
                            </itemtemplate>
                        </asp:TemplateField>
                </Columns>
      </asp:GridView>
                    </td>
                </tr>
            </table>
           
            </div>
</asp:Content>
