<%@ Page Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="GridView.aspx.cs" Inherits="WebApplication2.GridView" %>
 <asp:Content ID="contentHeader" runat="server" ContentPlaceHolderID="ContentPlaceHolder1" runtat="server">
        <div>
            <asp:GridView ID="Jobview" runat="server" AutoGenerateColumns="False" DataKeyNames="AccountId" AutoGenerateDeleteButton="True"
                AutoGenerateEditButton="True" onrowcancelingedit="GridView1_RowCancelingEdit"   
                    onrowdeleting="GridView1_RowDeleting" onrowediting="GridView1_RowEditing"   
                   >
                <Columns>
                    <asp:TemplateField HeaderText="AccountId" runat="server">
                <edititemtemplate>  
                                <asp:TextBox ID="TxtName" runat="server" Text='<%# Bind("AccountId") %>'></asp:TextBox> 
                                </edititemtemplate>
                <itemtemplate>  
                                <asp:Label ID="LabelName" runat="server" Text='<%# Bind("AccountId") %>'></asp:Label>  
                            </itemtemplate>
            </asp:TemplateField>
                     <asp:TemplateField HeaderText="FirstName" runat="server">
                <edititemtemplate>  
                                <asp:TextBox ID="TxtName" runat="server" Text='<%# Bind("FirstName") %>'></asp:TextBox> 
                                </edititemtemplate>
                <itemtemplate>  
                                <asp:Label ID="LabelName" runat="server" Text='<%# Bind("FirstName") %>'></asp:Label>  
                            </itemtemplate>
            </asp:TemplateField>
                    <asp:TemplateField HeaderText="Phone" runat="server">
                <edititemtemplate>  
                                <asp:TextBox ID="TxtPhone" runat="server" Text='<%# Bind("PhoneNumber") %>'></asp:TextBox> 
                                </edititemtemplate>
                <itemtemplate>  
                                <asp:Label ID="LabelPhone" runat="server" Text='<%# Bind("PhoneNumber") %>'></asp:Label>  
                            </itemtemplate>
                        </asp:TemplateField>
                </Columns>
            </asp:GridView>
        </div>
     </asp:Content>